package com.apollo.discounthunter.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MY_COLLECTION".
 */
public class MyCollection {

    /** Not-null value. */
    /**
     * 鎶樻墸淇℃伅鍞竴id
     */
    private String id;
    /**
     * 鎶樻墸淇℃伅涓嬪崟鍦板潃
     */
    private String web_url;
    /**
     * 鍞よ捣娣樺疂app鐨勬姌鎵ｄ俊鎭笅鍗曞湴鍧�
     */
    private String app_url;
    /**
     * 鎶樻墸淇℃伅鍥剧墖鍦板潃
     */
    private String pic;
    /**
     * 鎶樻墸淇℃伅鏍囬
     */
    private String title;
    /**
     * 鎶樻墸淇℃伅鎺ㄨ崘鐞嗙敱
     */
    private String reason;
    /**
     * 浠锋牸
     */
    private String price;
    /**
     * 
     */
    private String soldcount;
    /**
     * 
     */
    private String commission;
    /**
     * 
     */
    private String item_cat_id;
    /**
     * 
     */
    private String num_iid;
    /**
     * 
     */
    private String platform_id;
    /**
     * 
     */
    private String end_time;
    /**
     * 鍟嗗搧鏇存柊鏃堕棿
     */
    private String release_time;
    /**
     * 
     */
    private String eventid;
    /**
     * 
     */
    private String addtime;
    /**
     * 
     */
    private String seller_id;
    /**
     * 
     */
    private String quan_id;
    /**
     * 
     */
    private String quan_price;
    /**
     * 浼樻儬鍒搁摼鎺�
     */
    private String quan_link;
    /**
     * 缃《鏍囧織 闈�0缃《
     */
    private String flag;
    /**
     * 浼樻儬鍒告�绘暟
     */
    private String totalCount;
    /**
     * 浼樻儬鍒搁鍙栨�绘暟
     */
    private String appliedCount;

    public MyCollection() {
    }

    public MyCollection(String id) {
        this.id = id;
    }

    public MyCollection(String id, String web_url, String app_url, String pic, String title, String reason, String price, String soldcount, String commission, String item_cat_id, String num_iid, String platform_id, String end_time, String release_time, String eventid, String addtime, String seller_id, String quan_id, String quan_price, String quan_link, String flag, String totalCount, String appliedCount) {
        this.id = id;
        this.web_url = web_url;
        this.app_url = app_url;
        this.pic = pic;
        this.title = title;
        this.reason = reason;
        this.price = price;
        this.soldcount = soldcount;
        this.commission = commission;
        this.item_cat_id = item_cat_id;
        this.num_iid = num_iid;
        this.platform_id = platform_id;
        this.end_time = end_time;
        this.release_time = release_time;
        this.eventid = eventid;
        this.addtime = addtime;
        this.seller_id = seller_id;
        this.quan_id = quan_id;
        this.quan_price = quan_price;
        this.quan_link = quan_link;
        this.flag = flag;
        this.totalCount = totalCount;
        this.appliedCount = appliedCount;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getWeb_url() {
        return web_url;
    }

    public void setWeb_url(String web_url) {
        this.web_url = web_url;
    }

    public String getApp_url() {
        return app_url;
    }

    public void setApp_url(String app_url) {
        this.app_url = app_url;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getSoldcount() {
        return soldcount;
    }

    public void setSoldcount(String soldcount) {
        this.soldcount = soldcount;
    }

    public String getCommission() {
        return commission;
    }

    public void setCommission(String commission) {
        this.commission = commission;
    }

    public String getItem_cat_id() {
        return item_cat_id;
    }

    public void setItem_cat_id(String item_cat_id) {
        this.item_cat_id = item_cat_id;
    }

    public String getNum_iid() {
        return num_iid;
    }

    public void setNum_iid(String num_iid) {
        this.num_iid = num_iid;
    }

    public String getPlatform_id() {
        return platform_id;
    }

    public void setPlatform_id(String platform_id) {
        this.platform_id = platform_id;
    }

    public String getEnd_time() {
        return end_time;
    }

    public void setEnd_time(String end_time) {
        this.end_time = end_time;
    }

    public String getRelease_time() {
        return release_time;
    }

    public void setRelease_time(String release_time) {
        this.release_time = release_time;
    }

    public String getEventid() {
        return eventid;
    }

    public void setEventid(String eventid) {
        this.eventid = eventid;
    }

    public String getAddtime() {
        return addtime;
    }

    public void setAddtime(String addtime) {
        this.addtime = addtime;
    }

    public String getSeller_id() {
        return seller_id;
    }

    public void setSeller_id(String seller_id) {
        this.seller_id = seller_id;
    }

    public String getQuan_id() {
        return quan_id;
    }

    public void setQuan_id(String quan_id) {
        this.quan_id = quan_id;
    }

    public String getQuan_price() {
        return quan_price;
    }

    public void setQuan_price(String quan_price) {
        this.quan_price = quan_price;
    }

    public String getQuan_link() {
        return quan_link;
    }

    public void setQuan_link(String quan_link) {
        this.quan_link = quan_link;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getTotalCount() {
        return totalCount;
    }

    public void setTotalCount(String totalCount) {
        this.totalCount = totalCount;
    }

    public String getAppliedCount() {
        return appliedCount;
    }

    public void setAppliedCount(String appliedCount) {
        this.appliedCount = appliedCount;
    }

}
