package com.apollo.discounthunter.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEARCH_HISTORY".
 */
public class SearchHistory {

    /** Not-null value. */
    private String search;
    /** Not-null value. */
    private String time;

    public SearchHistory() {
    }

    public SearchHistory(String search, String time) {
        this.search = search;
        this.time = time;
    }

    /** Not-null value. */
    public String getSearch() {
        return search;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSearch(String search) {
        this.search = search;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

}
