package com.apollo.discounthunter.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.apollo.discounthunter.greendao.bean.SearchHistory;
import com.apollo.discounthunter.greendao.bean.MyCollection;

import com.apollo.discounthunter.greendao.dao.SearchHistoryDao;
import com.apollo.discounthunter.greendao.dao.MyCollectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig myCollectionDaoConfig;

    private final SearchHistoryDao searchHistoryDao;
    private final MyCollectionDao myCollectionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        myCollectionDaoConfig = daoConfigMap.get(MyCollectionDao.class).clone();
        myCollectionDaoConfig.initIdentityScope(type);

        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        myCollectionDao = new MyCollectionDao(myCollectionDaoConfig, this);

        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(MyCollection.class, myCollectionDao);
    }
    
    public void clear() {
        searchHistoryDaoConfig.getIdentityScope().clear();
        myCollectionDaoConfig.getIdentityScope().clear();
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public MyCollectionDao getMyCollectionDao() {
        return myCollectionDao;
    }

}
